version: "3.9"
services:
    api:
        container_name: registration
        restart: always
        build: .
        ports:
            - "8080:8080"
        depends_on: 
            - redis
            - rabbitmq
    redis:
        container_name: redis
        image: redis:alpine
        ports:
            - "6379:6379"
        restart: always
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management
        ports: 
            - "5672:5672"
            - "15672:15672"
        restart: always